### ISSUE TITLE
No need to wait after Wire.requestFrom() and it should not be followed by Wire.endTransmission().

### ISSUE THREAD

**Issue by Koepel** [ShVerni/RoboRuckus#2]
In the file "RoboRuckus/BotCode/Adafruit_HMC5883/Adafruit_HMC5883_U.cpp", you may remove the lines: "`while (Wire.available() < 6);`", and you may also remove the Wire.endTransmission() after a Wire.requestFrom().
Explanation: [Common-mistakes](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes), number 1 and 2.

See also: https://github.com/adafruit/Adafruit_HMC5883_Unified/issues/1

**Comment by ShVerni** [comment]
Thanks for the tips! I'm actually planning to switch to a different sensor in the near future since the HMC5883 board I was using has been discontinued. That being the case, I'm not particularly inclined to spend any time messing around with the library especially since it's currently working fine and I plan to dump it soon anyway. However, I'll definitely keep your tips in mind for the future, or if for some reason I am unable to switch to a different sensor.
